### ISSUE TITLE
这个翻译的很水

### ISSUE THREAD

**Issue by feifei435** [skyline75489/what-happens-when-zh_CN#1]
读起来很生涩，像是机器翻译。感觉PO主貌似也不是很懂的样子哦

**Comment by skyline75489** [comment]
我今天才开始翻译，自己确实也水平有限，随时欢迎PR！

**Comment by dopcn** [comment]
谷歌翻译很强大，可以先谷歌翻译第一版，再过滤语意不通:metal:

**Comment by skyline75489** [comment]
@dopcn  现在已经基本翻译完了，我自己也稍微润色了一下，已经没有之前那么生涩了

**Comment by dopcn** [comment]
@skyline75489 :wave:
