### ISSUE TITLE
当请求资源时应该会先检查缓存

### ISSUE THREAD

**Issue by cqupt-yifanwu** [skyline75489/what-happens-when-zh_CN#12]
- 缓存从网络中读取抵达的请求报文
- 缓存对保温进行解析并查找本地是否有副本可以用若没有就获取一份（向服务端）并将其保存在本地
- 如果有副本可以用需要对其新鲜度进行检测（通过Cache-Control和Expires首部），如果足够新鲜直接使用这个副本返回给服务端
- 如果新鲜度已过需要与服务端进行再验证（常用If-Modified-Since:Data或E-tag首部）如果服务端检查过之后文档未发生变化则返回一个新的过期时间，若发生了变化则返回一个新的资源。

**Comment by skyline75489** [comment]
What r u talking about, man...

**Comment by cqupt-yifanwu** [comment]
uhn? 缓存的检查啊，不对吗？

**Comment by skyline75489** [comment]
这个仓库只负责翻译[原仓库]( https://github.com/alex/what-happens-when)的内容，如果想添加内容可以去原仓库发 issue 或者 PR。
