### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by aloneZERO** [skyline75489/what-happens-when-zh_CN#14]
**HTTP 服务器请求处理** 部分

“HTTPD(HTTP Daemon) 在服务器端处理请求/相应”

请求/相应 --> 请求/响应
***
对了，我能否将文章转载到自己的博客呢？（原文地址和原仓库地址均会注明）

**Comment by skyline75489** [comment]
谢谢指出，我有点好奇，你是从哪里找到的这个项目呢？最近这个项目突然增加了很多访问量

**Comment by aloneZERO** [comment]
我是今天刷 [V2EX](https://www.v2ex.com/) 看到的，那个帖子不好找了。觉得很有意思，就想转载到博客上~

**Comment by skyline75489** [comment]
翻译内容同原仓库一样使用 CC0 协议发布，可以转载和再创作。
