### ISSUE TITLE
关于浏览器缓存没有提及奥

### ISSUE THREAD

**Issue by liujiangfeng** [skyline75489/what-happens-when-zh_CN#7]
# http 200(from cache) 和 304

http://stackoverflow.com/questions/1665082/http-status-code-200-cache-vs-status-code-304

在先前至少有过一次有效访问后，在以后对同一URI资源的请求中，浏览器只进行两种动作：
(1)直接在缓存中去获取内容。如果先前有效访问的响应头包含 Expires, max-age的话，“打开新窗口”、“输入URI回车”、“前一页”、“后一页”这些浏览器行为不会使浏览器在Expires, max-age设置的有效期时间内去访问服务器，而是在缓存中去获取内容，但是’”刷新’”或”重载”例外。
(2)访问服务器，根据服务器响应来获取内容。这种情况发生在设置no-cache等头标要求不缓存，或者是设置了 Expires,max-age但浏览器行为是“刷新”或“重载”时候。’Last-Modified’、’ETag’、’must-revalidate’ 等有些特殊，不直接受浏览器行为影响，它们必须访问服务器后，再由服务器判断是直接发送新的资源，还是发送一个304 Not Modfied让浏览器使用缓存中的资源。

内容来自
http://www.haidx.com/http-304-and-200-from-cache.html

**Comment by skyline75489** [comment]
304 提到了，在”HTTP 协议“那部分，200(from cache) 这个确实没有提到。有兴趣的话可以去原英文仓库提 PR 补充一下。这个仓库目前只管翻译英文仓库的内容。
